/* eslint-disable @next/next/no-sync-scripts */
import "./globals.css";
import { ThemeProvider } from "@/utils/material_tailwind";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body>
          {children}
          <Script src="../path/to/flowbite/dist/flowbite.min.js"></Script>
        </body>
      </html>
    </ThemeProvider>
  );
}
