import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/utils/material_tailwind'
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={inter.className}>{children}
          <Script src="../path/to/flowbite/dist/flowbite.min.js"></Script>
        </body>
      </html>
    </ThemeProvider>
  )
}
