"use client";

import {
    ThemeProvider, Button,
    Typography,
    List,
    ListItem,
    ListItemPrefix,
    ListItemSuffix,
    Chip,
    Accordion,
    AccordionHeader,
    AccordionBody,
    Menu,
    MenuHandler,
    MenuList,
    MenuItem,
    Avatar,
    IconButton,
    SpeedDial,
    SpeedDialHandler,
    SpeedDialContent,
    SpeedDialAction,
    Dialog,
    DialogHeader,
    DialogBody,
    DialogFooter,
    Card,
    CardBody,
    CardFooter,
    CardHeader,
    Textarea,
    Input,
    Select, Option,
    Alert,
    Checkbox,
    Tab,
    TabPanel,
    Tabs,
    TabsBody,
    TabsHeader
} from '@material-tailwind/react';

export {
    ThemeProvider,
    Button,
    Typography,
    List,
    ListItem,
    ListItemPrefix,
    ListItemSuffix,
    Chip,
    Accordion,
    AccordionHeader,
    AccordionBody,
    Menu,
    MenuHandler,
    MenuList,
    MenuItem,
    Avatar,
    IconButton,
    SpeedDial,
    SpeedDialHandler,
    SpeedDialContent,
    SpeedDialAction,
    Dialog,
    DialogHeader,
    DialogBody,
    DialogFooter,
    Card,
    CardBody,
    CardFooter,
    CardHeader,
    Textarea,
    Input,
    Option,
    Select,
    Alert,
    Checkbox,
    Tab,
    TabPanel,
    Tabs,
    TabsBody,
    TabsHeader
};